#!/usr/bin/env bash
# 404 Not Found Page
# Install Nginx
apt-get update
apt-get install -y nginx

# Define the custom header configuration
custom_header_conf="server_tokens off;
add_header X-Served-By \$hostname;"

# Update the default Nginx configuration file to include the custom header
echo "$custom_header_conf" | tee -a /etc/nginx/nginx.conf > /dev/null

# Restart Nginx to apply the changes
service nginx restart
