#!/bin/bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    timeout client  30000
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 183513-web-01:80 check
    server web-02 183513-web-02:80 check
EOF

# Replace STUDENT_ID with your actual student ID
sudo sed -i "s/183513/183513/g" /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart

# Enable HAProxy init script
sudo service haproxy enable
