#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this

awk '{count[$1" "$9]++} END {for (item in count) print count[item], item}' apache-access.log | sort -rn
