#!/usr/bin/env bash
# This script displays the time for 12hours and 59 minuites

i=0

while [ $i -lt 12 ]; do
	echo "Hour: $i"
	min=1
	while [ $min -lt 60 ]; do
		echo $min
		((min++))
	done
	((i++))
done
