#!/usr/bin/env bash
# Replace user directive in nginx.conf
sed -i 's/^user .*$/user nginx;/' /etc/nginx/nginx.conf

# Replace port number in the default site configuration
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart
