#!/usr/bin/env bash

# Modify the nginx.conf file to run Nginx as the nginx user
sed -i 's/user\s*root;/user nginx;/g' /etc/nginx/nginx.conf

# Modify the default site configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
